sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - mike@picknik.ai
before_install:
  - export DOCKER_IMAGE=moveit/moveit:master-source
env:
  matrix:
    - ROS_DISTRO=kinetic  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=./ur5_moveit_simple.rosinstall
    - ROS_DISTRO=kinetic  ROS_REPO=ros              TEST=clang-format
script:
  - source .travis/travis.sh
addons:
  # https://docs.travis-ci.com/user/ssh-known-hosts/
  ssh_known_hosts:
    - bitbucket.org
